language: java
jdk: openjdk11

stages:
  - name: build
  - name: release
    if: (branch = master) AND (tag =~ /^v*.$/)

jobs:
  include:
    - stage: build
      script: "./gradlew build --scan"
    - stage: release
      script: "./gradlew publishPlugin"

before_install:
  - echo -e "gradle.publish.key=$GRADLE_PUBLISH_KEY\ngradle.publish.secret=$GRADLE_PUBLISH_SECRET" > gradle.properties

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

env:
  global:
    - secure: bT0nLcB4Sh4cwUTHZ+j7UfClFi1B8x2w1OUnENSk+jbQt36DGC7tSyjWDtuDbCZPZ9540iBix1U9/LH6oXE4AheIIb21UDr9YJvRgaR8f4K6ha8nnV3+ZgjKdEZknu2ScnNVAX/CrZ0D8ja7HAqeE4TooWSg5Pg05xvCIrYHviClS1fo3oJqOqKsUFlAFWePGB6DY/j7odkdrMKQB6cQXjnqscdYqQY6N5+ps7q0UUMoXoDfasvoIRjEJjIVYu/CPnsi5W55olNYL2JflZcGuKnxn8AFO1kuqmMhSR6bcvLzmMPGDHPMrJD3UOWnyhOtby4HnsWbmel5Nzf9b6E3iKhTbGePSIPLWz22elI9LGRTPyHw+oSBHMjEqkqQbrhv7M5LVyfGG4QQb00CCZVug1W9F54BhmgweGHksjd+4e5Ere2Vxg+LD9P9MA2jRkhloTJ2h5wVWirumOAIH7pmE7vYzlaR5vz5D4rh+e4duDaBNiVwoq1736o2UIfxOqze+Bl2pnkUsyVBzJRhDps4NlpBf2Xm/l4ek2V8/vEe4e9S4g2JXTACahX1LDqS+YzMTcmepXto924eZ6TW9YoNtAMwRuxFEoQbQPVMAtsTZF3/LX8JEfg7Wm424WHW6V+E4Z2NErBN1R0k8iboRaTppk3b+3WCbamu+3zZjkyKo0E=
    - secure: sfZOdpbSBa/aeRSz/EVsxY0lTGd7PA4w2I7a8RZe//jNIGP/8Cql3s30lDgRBc1fy+siL0VQK+OEcAFoxwl5nALpRMXfIvpqrrtalw7faDOvvvxPmp72MQdf/JuyzJLxebaSActN0nw6AzsGB+95NfKBS6g++z9Td8KzP+Az4bp1Enr5YSkSj/5xP//TrpT13xntAMATshJQRCqmKqk9sYapL++aIqMb5y9AW09NR7cuKuyXC9RO3TzzW61QllDbUHLcPHexQdLpyZ4vxUBYb1jQ8J3choho4HrWV7oVbUPgPI4cpwz5b80GFSABEjy8YOfe8x5/M5CI2L6OObHotgHvSzYofn1EEKQCOrrYvfy60LEZVIsxZGRdDE27ymmJ58j3acRfoevRuhXQfbScOZseEfST5htnV5JILWzD5kSGhUXDv0HJcaFosSZHB3aSUCizmU3+FW5ESP3TrInzP4PCe/EvqtVDpn+Q9eH+Zq8Sx3qQptGkM3GHPt1JXd+xsg81WeymVD1azNnnCjFvvdsLM+dPEaY6TpgyJGijGLmFFQH4mh7s1Th5Smrn7ac/s3QBh26Rq3yXKJ1CH7pu5RZoLLCkSeARmLw4RS3BkgZVMa8z72mbVAoeMs8PgLCHaNxHDmcNoKTKQl5PL0kh+IssOWgAFLRGs+5+TukK3pk=
branches:
  only:
    - master
